services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      DATABASE_URL: postgres://go:go@postgres/go?sslmode=disable
      REDIS_ADDRESS: redis:6379
    networks:
      - dcard
  postgres:
    image: postgres:15.5-alpine
    restart: always
    environment:
      POSTGRES_DB: go
      POSTGRES_USER: go
      POSTGRES_PASSWORD: go
      PGDATA: /data/postgres
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/init.sql
      - dcard:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - dcard
  redis:
    image: redis:7.2.4-alpine
    ports:
      - 6379:6379
    networks:
      - dcard
volumes:
  dcard:
networks:
  dcard:
# find out your port
# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' postgres's_id
